# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8cf9c5fbcda87b0ab6dde851239301b73550a958a3362b69e2c72e099d980417b131adfff27cb0dc5e969589ea1b9efa2ad8f11b3ecfd22f46dd25013587645

test:
  secret_key_base: df2c63428859cba62c230322d69dd53da7047347f2c2b55a33c6876d04d55b0ad7af62d6ac84c4183d2171c5ab436ce48917419597bee3727971189822eb9463

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
